name: Hit Web Page Cron Job

on:
  schedule:
    - cron: '*/10 * * * *'    # Runs every 10 minutes, adjust as needed
   #- cron: '0 0 * * *' # Runs once per day , adjust as needed

jobs:
  hit-url:
    runs-on: ubuntu-latest

    steps:
      - name: Curl the web page
        run: curl -s https://onebyte-app-server.onrender.com/> /dev/null
